spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5434/docmind
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.open-in-view=false

 spring.ai.openai.api-key=YOUR_API_KEY_HERE
 spring.ai.openai.chat.model=gpt-4o-mini
 spring.ai.openai.embeddings.model=text-embedding-3-small